/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import model.Berkas_Lamaran;
import model.Pelamar;
import model.Perusahaan;

/**
 *
 * @author KNF
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form AplicationGUIPelamar
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar2 = new javax.swing.JScrollBar();
        pnlRegisterPerusahaan = new javax.swing.JTabbedPane();
        plRegistrasiPelamar = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtNo_hp = new javax.swing.JTextField();
        txtperusahaan_dituju = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();
        lbemail = new javax.swing.JLabel();
        lbAlamat = new javax.swing.JLabel();
        lbNo_hp = new javax.swing.JLabel();
        lbPerusahaan_dituju = new javax.swing.JLabel();
        btnSubmitPelamar = new javax.swing.JButton();
        lbbagian = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        lbLogo = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txDaftarPelamar = new javax.swing.JTextArea();
        plRegistrsasiPerusahaan = new javax.swing.JPanel();
        lbLokasi = new javax.swing.JLabel();
        txtLokasi = new javax.swing.JTextField();
        txtJmlLowongan = new javax.swing.JTextField();
        lbJmlLowongan = new javax.swing.JLabel();
        lbDaftarLowongan = new javax.swing.JLabel();
        cbDaftarLowongan = new javax.swing.JComboBox();
        lbJmlPelamar = new javax.swing.JLabel();
        txtJmlPelamar = new javax.swing.JTextField();
        btnSubmitPerusahaan = new javax.swing.JButton();
        lbNamaPerusahaan = new javax.swing.JLabel();
        txtNamePerusahaan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtgetDetil = new javax.swing.JTextArea();
        plDataPelamar = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDetilPelamar = new javax.swing.JTextArea();
        lbDetilPerlamar = new javax.swing.JLabel();
        plDataPerusahaan = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDetilPerusahaan = new javax.swing.JTextArea();
        lbDetilPerusahaan = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOKER");

        pnlRegisterPerusahaan.setBackground(new java.awt.Color(255, 255, 204));
        pnlRegisterPerusahaan.setToolTipText("");

        plRegistrasiPelamar.setBackground(new java.awt.Color(255, 255, 255));

        lbName.setText("Nama");

        lbemail.setText("E-mail");

        lbAlamat.setText("Alamat");

        lbNo_hp.setText("No_hp");

        lbPerusahaan_dituju.setText("Nama Perusahaan");

        btnSubmitPelamar.setText("Submit");
        btnSubmitPelamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitPelamarActionPerformed(evt);
            }
        });

        lbbagian.setText("Bagian");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Developer", "Administator", "General Manager", "Supervisor", "Marketing" }));

        lbLogo.setBackground(new java.awt.Color(0, 153, 102));
        lbLogo.setText("Masukan Data Diri Anda Sebagai Pelamar");

        txDaftarPelamar.setColumns(20);
        txDaftarPelamar.setRows(5);
        jScrollPane5.setViewportView(txDaftarPelamar);

        javax.swing.GroupLayout plRegistrasiPelamarLayout = new javax.swing.GroupLayout(plRegistrasiPelamar);
        plRegistrasiPelamar.setLayout(plRegistrasiPelamarLayout);
        plRegistrasiPelamarLayout.setHorizontalGroup(
            plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                        .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(btnSubmitPelamar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plRegistrasiPelamarLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbemail)
                                    .addComponent(lbAlamat)
                                    .addComponent(lbNo_hp)
                                    .addComponent(lbPerusahaan_dituju)
                                    .addComponent(lbbagian)
                                    .addComponent(lbName))
                                .addGap(39, 39, 39)
                                .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNo_hp, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtperusahaan_dituju, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbLogo)))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        plRegistrasiPelamarLayout.setVerticalGroup(
            plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                        .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbName))
                        .addGap(18, 18, 18)
                        .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbemail))
                        .addGap(14, 14, 14)
                        .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAlamat)
                            .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNo_hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNo_hp))
                        .addGap(24, 24, 24)
                        .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtperusahaan_dituju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPerusahaan_dituju))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbbagian)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5))
                .addGap(48, 48, 48)
                .addComponent(btnSubmitPelamar)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pnlRegisterPerusahaan.addTab("Register Pelamar", plRegistrasiPelamar);

        plRegistrsasiPerusahaan.setBackground(new java.awt.Color(255, 255, 255));

        lbLokasi.setText("Lokasi");

        lbJmlLowongan.setText("Jumlah Lowongan");

        lbDaftarLowongan.setText("Daftar Lowongan");

        cbDaftarLowongan.setBackground(new java.awt.Color(204, 204, 204));
        cbDaftarLowongan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Default", " " }));

        lbJmlPelamar.setText("Jumlah Pelamar");

        txtJmlPelamar.setEditable(false);
        txtJmlPelamar.setBackground(new java.awt.Color(204, 204, 204));

        btnSubmitPerusahaan.setText("Submit");
        btnSubmitPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitPerusahaanActionPerformed(evt);
            }
        });

        lbNamaPerusahaan.setText("Nama Perusahaan");

        jLabel1.setText("Pendaftaran Perusahaan");

        txtgetDetil.setEditable(false);
        txtgetDetil.setColumns(20);
        txtgetDetil.setRows(5);
        jScrollPane2.setViewportView(txtgetDetil);

        javax.swing.GroupLayout plRegistrsasiPerusahaanLayout = new javax.swing.GroupLayout(plRegistrsasiPerusahaan);
        plRegistrsasiPerusahaan.setLayout(plRegistrsasiPerusahaanLayout);
        plRegistrsasiPerusahaanLayout.setHorizontalGroup(
            plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plRegistrsasiPerusahaanLayout.createSequentialGroup()
                .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plRegistrsasiPerusahaanLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(plRegistrsasiPerusahaanLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(plRegistrsasiPerusahaanLayout.createSequentialGroup()
                                .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbLokasi)
                                    .addComponent(lbNamaPerusahaan)
                                    .addComponent(lbJmlLowongan)
                                    .addComponent(lbJmlPelamar)
                                    .addComponent(lbDaftarLowongan))
                                .addGap(66, 66, 66)
                                .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamePerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJmlLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJmlPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDaftarLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnSubmitPerusahaan))
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        plRegistrsasiPerusahaanLayout.setVerticalGroup(
            plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plRegistrsasiPerusahaanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plRegistrsasiPerusahaanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNamaPerusahaan)
                            .addComponent(txtNamePerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLokasi))
                        .addGap(34, 34, 34)
                        .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJmlLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbJmlLowongan))
                        .addGap(34, 34, 34)
                        .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJmlPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbJmlPelamar))
                        .addGap(41, 41, 41)
                        .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDaftarLowongan)
                            .addComponent(cbDaftarLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(btnSubmitPerusahaan)
                        .addGap(84, 84, 84))
                    .addGroup(plRegistrsasiPerusahaanLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnlRegisterPerusahaan.addTab("Register Perusahaan", plRegistrsasiPerusahaan);

        plDataPelamar.setBackground(new java.awt.Color(255, 255, 255));

        txtDetilPelamar.setEditable(false);
        txtDetilPelamar.setColumns(20);
        txtDetilPelamar.setRows(5);
        jScrollPane3.setViewportView(txtDetilPelamar);

        lbDetilPerlamar.setText("Daftar Pelamar");

        javax.swing.GroupLayout plDataPelamarLayout = new javax.swing.GroupLayout(plDataPelamar);
        plDataPelamar.setLayout(plDataPelamarLayout);
        plDataPelamarLayout.setHorizontalGroup(
            plDataPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plDataPelamarLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lbDetilPerlamar)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        plDataPelamarLayout.setVerticalGroup(
            plDataPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDataPelamarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(plDataPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDetilPerlamar))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pnlRegisterPerusahaan.addTab("Data Pelamar", plDataPelamar);

        plDataPerusahaan.setBackground(new java.awt.Color(255, 255, 255));

        txtDetilPerusahaan.setEditable(false);
        txtDetilPerusahaan.setColumns(20);
        txtDetilPerusahaan.setRows(5);
        jScrollPane4.setViewportView(txtDetilPerusahaan);

        lbDetilPerusahaan.setText("Data Perusahaan");

        javax.swing.GroupLayout plDataPerusahaanLayout = new javax.swing.GroupLayout(plDataPerusahaan);
        plDataPerusahaan.setLayout(plDataPerusahaanLayout);
        plDataPerusahaanLayout.setHorizontalGroup(
            plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plDataPerusahaanLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lbDetilPerusahaan)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        plDataPerusahaanLayout.setVerticalGroup(
            plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDataPerusahaanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDetilPerusahaan))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pnlRegisterPerusahaan.addTab("Data Perusahaan", plDataPerusahaan);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegisterPerusahaan)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegisterPerusahaan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSubmitPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitPerusahaanActionPerformed
        // TODO add your handling code here:
        String getNamePerusahaan = txtNamePerusahaan.getText();
        String getLokasi = txtLokasi.getText();
        Perusahaan perusahaan = new Perusahaan(getNamePerusahaan, getLokasi);
        txtNamePerusahaan.setText("");
        txtLokasi.setText("");
        txtJmlLowongan.setText("");
        txtJmlPelamar.setText("");
        txtgetDetil.setText("Nama Perusahaan : " + perusahaan.getNama()
            + System.lineSeparator() + "Lokasi Perusahaan : "+perusahaan.getLokasi());
        System.out.println("INPUT PERUSAHAAN SUKSES!");
    }//GEN-LAST:event_btnSubmitPerusahaanActionPerformed

    private void btnSubmitPelamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitPelamarActionPerformed
        // TODO add your handling code here:
        String getname = txtName.getText();
        String getBerkas=txtperusahaan_dituju.getText();
        Pelamar pelamar=new Pelamar(getname);
        pelamar.setEmail(txtemail.getText());
        pelamar.setAlamat(txtalamat.getText());
        pelamar.setNo_hp(txtNo_hp.getText());
        pelamar.setBerkas(null);
        txtName.setText("");
        txtemail.setText("");
        txtalamat.setText("");
        txtNo_hp.setText("");
        txtperusahaan_dituju.setText("");

//        txtGet.setText("Nama : "+pelamar.getNama()
//            +"\nE-mail : "+pelamar.getEmail()
//            +"\nAlamat : "+pelamar.getAlamat()
//            +"\nNo Hp : "+pelamar.getNo_hp());
        //                +"/nPerusahaan yang dituju : "+pelamar.getBerkas().getPerusahaan_dituju());

        System.out.println("BERHASIL INPUT");
    }//GEN-LAST:event_btnSubmitPelamarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubmitPelamar;
    private javax.swing.JButton btnSubmitPerusahaan;
    private javax.swing.JComboBox cbDaftarLowongan;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbDaftarLowongan;
    private javax.swing.JLabel lbDetilPerlamar;
    private javax.swing.JLabel lbDetilPerusahaan;
    private javax.swing.JLabel lbJmlLowongan;
    private javax.swing.JLabel lbJmlPelamar;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbLokasi;
    private javax.swing.JLabel lbNamaPerusahaan;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbNo_hp;
    private javax.swing.JLabel lbPerusahaan_dituju;
    private javax.swing.JLabel lbbagian;
    private javax.swing.JLabel lbemail;
    private javax.swing.JPanel plDataPelamar;
    private javax.swing.JPanel plDataPerusahaan;
    private javax.swing.JPanel plRegistrasiPelamar;
    private javax.swing.JPanel plRegistrsasiPerusahaan;
    private javax.swing.JTabbedPane pnlRegisterPerusahaan;
    private javax.swing.JTextArea txDaftarPelamar;
    private javax.swing.JTextArea txtDetilPelamar;
    private javax.swing.JTextArea txtDetilPerusahaan;
    private javax.swing.JTextField txtJmlLowongan;
    private javax.swing.JTextField txtJmlPelamar;
    private javax.swing.JTextField txtLokasi;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNamePerusahaan;
    private javax.swing.JTextField txtNo_hp;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextArea txtgetDetil;
    private javax.swing.JTextField txtperusahaan_dituju;
    // End of variables declaration//GEN-END:variables
    
    public void setDaftarPelamar(String s){
        txDaftarPelamar.setText(s);
    }
    
    void addActionListener(ActionListener e) {
        btnSubmitPelamar.addActionListener(e);
        
    }

    void setDaftarPeserta(String viewPelamar) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
