/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.management.remote.JMXConnectorFactory;
import javax.swing.JOptionPane;
import model.Berkas_Lamaran;
import model.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KNF
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form AplicationGUIPelamar
     */
    Database db = new Database();
//    PelamarController clPelamar = new PelamarController();
    
    public View() {
        initComponents();    
//        db.connect();
        show_pelamarlist_in_table();
        show_perusahaanlist_in_table();
        show_pelamarlist_in_berkas();
        show_perusahaanlist_in_lowongan();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar2 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlRegisterBerkas = new javax.swing.JTabbedPane();
        plRegistrasiPelamar = new javax.swing.JPanel();
        txtNamaPelamar = new javax.swing.JTextField();
        txtEmailPelamar = new javax.swing.JTextField();
        txtAlamatPelamar = new javax.swing.JTextField();
        txtNohpPelamar = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();
        lbemail = new javax.swing.JLabel();
        lbAlamat = new javax.swing.JLabel();
        lbNo_hp = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablePelamar = new javax.swing.JTable();
        btnInsertPelamar = new javax.swing.JButton();
        btnUpdatePelamar = new javax.swing.JButton();
        lbName1 = new javax.swing.JLabel();
        txtIdPelamar = new javax.swing.JTextField();
        btnDeletePelamar = new javax.swing.JButton();
        plRegistrsasiPerusahaan = new javax.swing.JPanel();
        lbLokasi = new javax.swing.JLabel();
        txtLokasiPerusahaan = new javax.swing.JTextField();
        lbNamaPerusahaan = new javax.swing.JLabel();
        txtNamaPerusahaan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtIdPerusahaan = new javax.swing.JTextField();
        lbNamaPerusahaan1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablePerusahaan = new javax.swing.JTable();
        btnInsertPerusahaan = new javax.swing.JButton();
        btnUpdatePerusahaan = new javax.swing.JButton();
        btnDeletePerusahaan = new javax.swing.JButton();
        plDataPelamar = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablePelamarOnBerkas = new javax.swing.JTable();
        plDataPerusahaan = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablePerusahaanOnLowongan = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        tableLowongan = new javax.swing.JTable();
        lbNamaPerusahaan2 = new javax.swing.JLabel();
        txtIdLowongan = new javax.swing.JTextField();
        lbNamaPerusahaan3 = new javax.swing.JLabel();
        txtNamaLowongan = new javax.swing.JTextField();
        lbLokasi1 = new javax.swing.JLabel();
        txtJumlahLowongan = new javax.swing.JTextField();
        btnDeleteLowongan = new javax.swing.JButton();
        btnUpdateLowongan = new javax.swing.JButton();
        btnInsertLowongan = new javax.swing.JButton();
        lbLokasi2 = new javax.swing.JLabel();
        txtIdPerusahaanLowongan = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOKER");

        pnlRegisterBerkas.setBackground(new java.awt.Color(255, 255, 204));
        pnlRegisterBerkas.setToolTipText("");
        pnlRegisterBerkas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRegisterBerkasMouseClicked(evt);
            }
        });

        plRegistrasiPelamar.setBackground(new java.awt.Color(255, 255, 255));

        lbName.setText("Nama");

        lbemail.setText("E-mail");

        lbAlamat.setText("Alamat");

        lbNo_hp.setText("No_hp");

        lbLogo.setBackground(new java.awt.Color(0, 153, 102));
        lbLogo.setText("Masukan Data Diri Anda Sebagai Pelamar");

        tablePelamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Alamat", "E-mail", "No HP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePelamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePelamarMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tablePelamar);
        if (tablePelamar.getColumnModel().getColumnCount() > 0) {
            tablePelamar.getColumnModel().getColumn(0).setMaxWidth(40);
            tablePelamar.getColumnModel().getColumn(2).setHeaderValue("Alamat");
            tablePelamar.getColumnModel().getColumn(3).setHeaderValue("E-mail");
            tablePelamar.getColumnModel().getColumn(4).setHeaderValue("No HP");
        }

        btnInsertPelamar.setText("INSERT");
        btnInsertPelamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertPelamarActionPerformed(evt);
            }
        });

        btnUpdatePelamar.setText("UPDATE");
        btnUpdatePelamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePelamarActionPerformed(evt);
            }
        });

        lbName1.setText("ID");

        btnDeletePelamar.setText("DELETE");
        btnDeletePelamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePelamarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plRegistrasiPelamarLayout = new javax.swing.GroupLayout(plRegistrasiPelamar);
        plRegistrasiPelamar.setLayout(plRegistrasiPelamarLayout);
        plRegistrasiPelamarLayout.setHorizontalGroup(
            plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbLogo))
                    .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                                .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbAlamat)
                                    .addComponent(lbemail)
                                    .addComponent(lbName)
                                    .addComponent(lbName1))
                                .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(txtIdPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plRegistrasiPelamarLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAlamatPelamar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmailPelamar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNamaPelamar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                                .addComponent(lbNo_hp)
                                .addGap(39, 39, 39)
                                .addComponent(txtNohpPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                                .addComponent(btnDeletePelamar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdatePelamar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInsertPelamar)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        plRegistrasiPelamarLayout.setVerticalGroup(
            plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbName1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbemail))
                        .addGap(18, 18, 18)
                        .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlamatPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAlamat))
                        .addGap(17, 17, 17)
                        .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNohpPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNo_hp))
                        .addGap(43, 43, 43)
                        .addGroup(plRegistrasiPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsertPelamar)
                            .addComponent(btnUpdatePelamar)
                            .addComponent(btnDeletePelamar)))
                    .addGroup(plRegistrasiPelamarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pnlRegisterBerkas.addTab("Register Pelamar", plRegistrasiPelamar);

        plRegistrsasiPerusahaan.setBackground(new java.awt.Color(255, 255, 255));

        lbLokasi.setText("Lokasi");

        lbNamaPerusahaan.setText("Nama Perusahaan");

        jLabel1.setText("Pendaftaran Perusahaan");

        lbNamaPerusahaan1.setText("ID");

        tablePerusahaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Perusahaan", "Nama", "Lokasi"
            }
        ));
        tablePerusahaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePerusahaanMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tablePerusahaan);

        btnInsertPerusahaan.setText("INSERT");
        btnInsertPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertPerusahaanActionPerformed(evt);
            }
        });

        btnUpdatePerusahaan.setText("UPDATE");
        btnUpdatePerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePerusahaanActionPerformed(evt);
            }
        });

        btnDeletePerusahaan.setText("DELETE");
        btnDeletePerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePerusahaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plRegistrsasiPerusahaanLayout = new javax.swing.GroupLayout(plRegistrsasiPerusahaan);
        plRegistrsasiPerusahaan.setLayout(plRegistrsasiPerusahaanLayout);
        plRegistrsasiPerusahaanLayout.setHorizontalGroup(
            plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plRegistrsasiPerusahaanLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(plRegistrsasiPerusahaanLayout.createSequentialGroup()
                        .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(plRegistrsasiPerusahaanLayout.createSequentialGroup()
                                .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbNamaPerusahaan)
                                    .addComponent(lbLokasi)
                                    .addComponent(lbNamaPerusahaan1))
                                .addGap(66, 66, 66)
                                .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLokasiPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamaPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(plRegistrsasiPerusahaanLayout.createSequentialGroup()
                                .addComponent(btnDeletePerusahaan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdatePerusahaan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnInsertPerusahaan)))
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        plRegistrsasiPerusahaanLayout.setVerticalGroup(
            plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plRegistrsasiPerusahaanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(plRegistrsasiPerusahaanLayout.createSequentialGroup()
                        .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNamaPerusahaan1))
                        .addGap(18, 18, 18)
                        .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNamaPerusahaan))
                        .addGap(18, 18, 18)
                        .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLokasiPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLokasi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(plRegistrsasiPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsertPerusahaan)
                            .addComponent(btnUpdatePerusahaan)
                            .addComponent(btnDeletePerusahaan)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(201, 201, 201))
        );

        pnlRegisterBerkas.addTab("Register Perusahaan", plRegistrsasiPerusahaan);

        plDataPelamar.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        tablePelamarOnBerkas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama"
            }
        ));
        tablePelamarOnBerkas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePelamarOnBerkasMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tablePelamarOnBerkas);
        if (tablePelamarOnBerkas.getColumnModel().getColumnCount() > 0) {
            tablePelamarOnBerkas.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        javax.swing.GroupLayout plDataPelamarLayout = new javax.swing.GroupLayout(plDataPelamar);
        plDataPelamar.setLayout(plDataPelamarLayout);
        plDataPelamarLayout.setHorizontalGroup(
            plDataPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDataPelamarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 239, Short.MAX_VALUE))
        );
        plDataPelamarLayout.setVerticalGroup(
            plDataPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDataPelamarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plDataPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pnlRegisterBerkas.addTab("Data Berkas Pelamar", plDataPelamar);

        plDataPerusahaan.setBackground(new java.awt.Color(255, 255, 255));

        tablePerusahaanOnLowongan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Perusahaan"
            }
        ));
        tablePerusahaanOnLowongan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePerusahaanOnLowonganMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tablePerusahaanOnLowongan);
        if (tablePerusahaanOnLowongan.getColumnModel().getColumnCount() > 0) {
            tablePerusahaanOnLowongan.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        tableLowongan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Bagian", "Jumlah Lowongan", "ID Perusahaan"
            }
        ));
        tableLowongan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLowonganMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(tableLowongan);
        if (tableLowongan.getColumnModel().getColumnCount() > 0) {
            tableLowongan.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        lbNamaPerusahaan2.setText("ID Lowongan");

        lbNamaPerusahaan3.setText("Nama Lowongan");

        lbLokasi1.setText("Jumlah lowongan");

        btnDeleteLowongan.setText("DELETE");
        btnDeleteLowongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLowonganActionPerformed(evt);
            }
        });

        btnUpdateLowongan.setText("UPDATE");
        btnUpdateLowongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLowonganActionPerformed(evt);
            }
        });

        btnInsertLowongan.setText("INSERT");
        btnInsertLowongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertLowonganActionPerformed(evt);
            }
        });

        lbLokasi2.setText("ID Perusahaan");

        javax.swing.GroupLayout plDataPerusahaanLayout = new javax.swing.GroupLayout(plDataPerusahaan);
        plDataPerusahaan.setLayout(plDataPerusahaanLayout);
        plDataPerusahaanLayout.setHorizontalGroup(
            plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDataPerusahaanLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plDataPerusahaanLayout.createSequentialGroup()
                        .addComponent(btnDeleteLowongan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateLowongan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInsertLowongan))
                    .addGroup(plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(plDataPerusahaanLayout.createSequentialGroup()
                            .addComponent(lbLokasi2)
                            .addGap(18, 18, 18)
                            .addComponent(txtIdPerusahaanLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(plDataPerusahaanLayout.createSequentialGroup()
                            .addGroup(plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbNamaPerusahaan3)
                                .addComponent(lbLokasi1)
                                .addComponent(lbNamaPerusahaan2))
                            .addGap(18, 18, 18)
                            .addGroup(plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtJumlahLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNamaLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIdLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 64, Short.MAX_VALUE))
        );
        plDataPerusahaanLayout.setVerticalGroup(
            plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDataPerusahaanLayout.createSequentialGroup()
                .addGroup(plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plDataPerusahaanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(plDataPerusahaanLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbLokasi1)
                            .addGroup(plDataPerusahaanLayout.createSequentialGroup()
                                .addGroup(plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNamaPerusahaan2))
                                .addGap(18, 18, 18)
                                .addGroup(plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNamaLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNamaPerusahaan3))
                                .addGap(18, 18, 18)
                                .addComponent(txtJumlahLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdPerusahaanLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLokasi2))
                        .addGap(31, 31, 31)
                        .addGroup(plDataPerusahaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsertLowongan)
                            .addComponent(btnUpdateLowongan)
                            .addComponent(btnDeleteLowongan))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pnlRegisterBerkas.addTab("Data Lowongan", plDataPerusahaan);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlRegisterBerkas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegisterBerkas, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnInsertPelamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertPelamarActionPerformed
        // TODO add your handling code here:
        if (checkInputPelamar()){
            try {
                Connection con = db.getConnection();
                PreparedStatement ps = con.prepareStatement("INSERT INTO Pelamar(Nama, Alamat, Email, Nohp) values (?,?,?,?)");
                ps.setString(1, txtNamaPelamar.getText());
                ps.setString(2, txtAlamatPelamar.getText());
                ps.setString(3, txtEmailPelamar.getText());
                ps.setString(4, txtNohpPelamar.getText());
                ps.executeUpdate();
                
                show_pelamarlist_in_table();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "One or More fields are Empty!");
        }
    }//GEN-LAST:event_btnInsertPelamarActionPerformed

    private void btnUpdatePelamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePelamarActionPerformed
        // TODO add your handling code here:
        if (checkInputPelamar()&& checkIdInputPelamar()){
            String UpdateQuery = null;
            PreparedStatement ps = null;
            Connection con = db.getConnection();
            
            UpdateQuery = "UPDATE pelamar SET nama = ?, alamat = ?, email = ?, nohp = ? where id = ?";
            try {
                ps = con.prepareStatement(UpdateQuery);
                
                ps.setString(1, txtNamaPelamar.getText());
                ps.setString(2, txtAlamatPelamar.getText());
                ps.setString(3, txtEmailPelamar.getText());
                ps.setString(4, txtNohpPelamar.getText());
                ps.setInt(6, Integer.parseInt(txtIdPelamar.getText()));
                
                ps.executeUpdate();
                
                show_pelamarlist_in_table();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in all of the fields");
        }
    }//GEN-LAST:event_btnUpdatePelamarActionPerformed

    private void btnDeletePelamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePelamarActionPerformed
        // TODO add your handling code here:
        if (checkIdInputPelamar()){
            try {
                Connection con = db.getConnection();
                String DeleteQuery = "DELETE FROM Pelamar where id = ?";
                PreparedStatement ps = null;
                ps = con.prepareStatement(DeleteQuery);
                
                ps.setInt(1, Integer.parseInt(txtIdPelamar.getText()));
                ps.executeUpdate();
                
                show_pelamarlist_in_table();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Pelamar id: " + txtIdPelamar.getText() + " not deleted");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please input the Pelamar id");
        }
    }//GEN-LAST:event_btnDeletePelamarActionPerformed

    private void tablePelamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePelamarMouseClicked
        // TODO add your handling code here:
        int index = tablePelamar.getSelectedRow();
        showEachPelamar(index);
    }//GEN-LAST:event_tablePelamarMouseClicked

    private void btnInsertPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertPerusahaanActionPerformed
        // TODO add your handling code here:
        if (checkInputPerusahaan()){
            try {
                Connection con = db.getConnection();
                PreparedStatement ps = con.prepareStatement("INSERT INTO Perusahaan(Nama, Lokasi) values (?,?)");
                ps.setString(1, txtNamaPerusahaan.getText());
                ps.setString(2, txtLokasiPerusahaan.getText());
                ps.executeUpdate();
                
                show_perusahaanlist_in_table();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "One or More fields are Empty!");
        }
    }//GEN-LAST:event_btnInsertPerusahaanActionPerformed

    private void tablePerusahaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePerusahaanMouseClicked
        // TODO add your handling code here:
        int index = tablePerusahaan.getSelectedRow();
        showEachPerusahaan(index);
    }//GEN-LAST:event_tablePerusahaanMouseClicked

    private void btnUpdatePerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePerusahaanActionPerformed
        if (checkInputPerusahaan() && checkIdInputPerusahaan()){
            String UpdateQuery = null;
            PreparedStatement ps = null;
            Connection con = db.getConnection();
            
            UpdateQuery = "UPDATE Perusahaan SET nama = ?, lokasi = ? where id = ?";
            try {
                ps = con.prepareStatement(UpdateQuery);
                
                ps.setString(1, txtNamaPerusahaan.getText());
                ps.setString(2, txtLokasiPerusahaan.getText());
                ps.setInt(3, Integer.parseInt(txtIdPerusahaan.getText()));
                
                ps.executeUpdate();
                
                show_perusahaanlist_in_table();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in all of the fields");
        }
    }//GEN-LAST:event_btnUpdatePerusahaanActionPerformed

    private void btnDeletePerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePerusahaanActionPerformed
        if (checkIdInputPerusahaan()){
            try {
                Connection con = db.getConnection();
                String DeleteQuery = "DELETE FROM Perusahaan where id = ?";
                PreparedStatement ps = null;
                ps = con.prepareStatement(DeleteQuery);
                
                ps.setInt(1, Integer.parseInt(txtIdPerusahaan.getText()));
                ps.executeUpdate();
                
                show_perusahaanlist_in_table();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Perusahaan id: " + txtIdPerusahaan.getText() + " not deleted");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please input the Perusahaan id");
        }
    }//GEN-LAST:event_btnDeletePerusahaanActionPerformed

    private void tablePelamarOnBerkasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePelamarOnBerkasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePelamarOnBerkasMouseClicked

    private void tablePerusahaanOnLowonganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePerusahaanOnLowonganMouseClicked
        int index = tablePerusahaanOnLowongan.getSelectedRow();
        Connection con = db.getConnection();
        String query = "SELECT * FROM Perusahaan";
//        PreparedStatement ps = con.prepareStatement(sql);
        Statement st;
        ResultSet rs;
        try {
            
            st = con.createStatement();
            rs = st.executeQuery(query);
            Perusahaan perusahaan;
            
            for (int i = 0; i <= index; i++) {
                rs.next();
            }
            perusahaan = new Perusahaan(rs.getString("id"), rs.getString("nama"), rs.getString("lokasi"));
//            perusahaan = (Perusahaan) rs.getObject(index);
            show_lowonganlist(perusahaan);
        } catch (SQLException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        show_lowonganlist(index);
    }//GEN-LAST:event_tablePerusahaanOnLowonganMouseClicked

    private void pnlRegisterBerkasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegisterBerkasMouseClicked
        // TODO add your handling code here:
        show_perusahaanlist_in_lowongan();
        show_perusahaanlist_in_table();
        show_pelamarlist_in_berkas();
        show_pelamarlist_in_table();
    }//GEN-LAST:event_pnlRegisterBerkasMouseClicked

    private void btnDeleteLowonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLowonganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteLowonganActionPerformed

    private void btnUpdateLowonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLowonganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateLowonganActionPerformed

    private void btnInsertLowonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertLowonganActionPerformed
        if (checkInputLowongan()){
            try {
                Connection con = db.getConnection();
                PreparedStatement ps = con.prepareStatement("INSERT INTO Lowongan(Nama, jumlah_lowongan, idperusahaan) values (?,?,?)");
                ps.setString(1, txtNamaLowongan.getText());
                ps.setString(2, txtJumlahLowongan.getText());
                ps.setString(3, txtIdPerusahaanLowongan.getText());
                ps.executeUpdate();
                
                show_perusahaanlist_in_table();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Perusahaan tidak ditemukan!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "One or More fields are Empty!");
        }
    }//GEN-LAST:event_btnInsertLowonganActionPerformed

    private void tableLowonganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLowonganMouseClicked
        // TODO add your handling code here:
        int index = tableLowongan.getSelectedRow();
        int row = tableLowongan.getRowCount();
        int column = tableLowongan.getColumnCount();
        ArrayList<Object> s = new ArrayList();
        for (int i = 0; i  < column; i++) {
                s.add(tableLowongan.getValueAt(index, i));
        }
        txtIdLowongan.setText(s.get(0).toString());
        txtNamaLowongan.setText(s.get(1).toString());
        txtJumlahLowongan.setText(s.get(2).toString());
        txtIdPerusahaanLowongan.setText(s.get(3).toString());
    }//GEN-LAST:event_tableLowonganMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteLowongan;
    private javax.swing.JButton btnDeletePelamar;
    private javax.swing.JButton btnDeletePerusahaan;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsertLowongan;
    private javax.swing.JButton btnInsertPelamar;
    private javax.swing.JButton btnInsertPerusahaan;
    private javax.swing.JButton btnUpdateLowongan;
    private javax.swing.JButton btnUpdatePelamar;
    private javax.swing.JButton btnUpdatePerusahaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbLokasi;
    private javax.swing.JLabel lbLokasi1;
    private javax.swing.JLabel lbLokasi2;
    private javax.swing.JLabel lbNamaPerusahaan;
    private javax.swing.JLabel lbNamaPerusahaan1;
    private javax.swing.JLabel lbNamaPerusahaan2;
    private javax.swing.JLabel lbNamaPerusahaan3;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbName1;
    private javax.swing.JLabel lbNo_hp;
    private javax.swing.JLabel lbemail;
    private javax.swing.JPanel plDataPelamar;
    private javax.swing.JPanel plDataPerusahaan;
    private javax.swing.JPanel plRegistrasiPelamar;
    private javax.swing.JPanel plRegistrsasiPerusahaan;
    private javax.swing.JTabbedPane pnlRegisterBerkas;
    private javax.swing.JTable tableLowongan;
    private javax.swing.JTable tablePelamar;
    private javax.swing.JTable tablePelamarOnBerkas;
    private javax.swing.JTable tablePerusahaan;
    private javax.swing.JTable tablePerusahaanOnLowongan;
    private javax.swing.JTextField txtAlamatPelamar;
    private javax.swing.JTextField txtEmailPelamar;
    private javax.swing.JTextField txtIdLowongan;
    private javax.swing.JTextField txtIdPelamar;
    private javax.swing.JTextField txtIdPerusahaan;
    private javax.swing.JTextField txtIdPerusahaanLowongan;
    private javax.swing.JTextField txtJumlahLowongan;
    private javax.swing.JTextField txtLokasiPerusahaan;
    private javax.swing.JTextField txtNamaLowongan;
    private javax.swing.JTextField txtNamaPelamar;
    private javax.swing.JTextField txtNamaPerusahaan;
    private javax.swing.JTextField txtNohpPelamar;
    // End of variables declaration//GEN-END:variables

    public boolean checkInputPelamar(){
        return !("".equals(txtNamaPelamar.getText())
                || "".equals(txtAlamatPelamar.getText())
                || "".equals(txtEmailPelamar.getText())
                || "".equals(txtNohpPelamar.getText()));
    }
    
    public boolean checkIdInputPelamar(){
        return !"".equals(txtIdPelamar.getText());
    }
    
    public ArrayList<Pelamar> getPelamarList(){
        
            ArrayList<Pelamar> pelamarList = new ArrayList<>();
            Connection con = db.getConnection();
            String query = "SELECT * from Pelamar";

            Statement st;
            ResultSet rs;
        try {
            
            st = con.createStatement();
            rs = st.executeQuery(query);
            Pelamar pelamar;
            
            while (rs.next()) {
                pelamar = new Pelamar(rs.getString("id"), rs.getString("nama"), rs.getString("alamat"),rs.getString("email"), rs.getString("nohp"));
                pelamarList.add(pelamar);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
        return pelamarList;
    }
    
    public void show_pelamarlist_in_table(){
        ArrayList<Pelamar> list = getPelamarList();
        DefaultTableModel model = (DefaultTableModel) tablePelamar.getModel();
        
//        CLEAR TABLE
        model.setRowCount(0);
        
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getNama();
            row[2] = list.get(i).getAlamat();
            row[3] = list.get(i).getEmail();
            row[4] = list.get(i).getNo_hp();
            
            model.addRow(row);
        }
    }
    
    public void showEachPelamar(int index){
        txtIdPelamar.setText(Integer.toString(getPelamarList().get(index).getId()));
        txtNamaPelamar.setText(getPelamarList().get(index).getNama());
        txtAlamatPelamar.setText(getPelamarList().get(index).getAlamat());
        txtEmailPelamar.setText(getPelamarList().get(index).getEmail());
        txtNohpPelamar.setText(getPelamarList().get(index).getNo_hp());
    }

    private boolean checkInputPerusahaan() {
        return !("".equals(txtNamaPerusahaan.getText()) || "".equals(txtLokasiPerusahaan.getText()));
    }
    
    public boolean checkIdInputPerusahaan(){
        return !"".equals(txtIdPerusahaan.getText());
    }
    
    public ArrayList<Perusahaan> getPerusahaanList(){
        
            ArrayList<Perusahaan> perusahaanList = new ArrayList<>();
            Connection con = db.getConnection();
            String query = "SELECT * from Perusahaan";

            Statement st;
            ResultSet rs;
        try {
            
            st = con.createStatement();
            rs = st.executeQuery(query);
            Perusahaan perusahaan;
            
            while (rs.next()) {
                perusahaan = new Perusahaan(rs.getString("id"), rs.getString("nama"), rs.getString("lokasi"));
                perusahaanList.add(perusahaan);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
        return perusahaanList;
    }
    
    public void show_perusahaanlist_in_table(){
        
    }
    
    public void showEachPerusahaan(int index){
        txtIdPerusahaan.setText(Integer.toString(getPerusahaanList().get(index).getId()));
        txtNamaPerusahaan.setText(getPerusahaanList().get(index).getNama());
        txtLokasiPerusahaan.setText(getPerusahaanList().get(index).getLokasi());
    }
    
    
    public void show_pelamarlist_in_berkas(){
        ArrayList<Pelamar> list = getPelamarList();
        DefaultTableModel model = (DefaultTableModel) tablePelamarOnBerkas.getModel();
        
//        CLEAR TABLE
        model.setRowCount(0);
        
        Object[] row = new Object[2];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getNama();
            
            model.addRow(row);
        }
    }
    
    
//    ------------- END BERKAS ----------------------------
    
    public void show_perusahaanlist_in_lowongan(){
        ArrayList<Perusahaan> list = getPerusahaanList();
        DefaultTableModel model = (DefaultTableModel) tablePerusahaanOnLowongan.getModel();
        
//        CLEAR TABLE
        model.setRowCount(0);
        
        Object[] row = new Object[2];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getNama();
            
            model.addRow(row);
        }
    }
    public boolean checkInputLowongan(){
        return !("".equals(txtNamaLowongan.getText()) || "".equals(txtJumlahLowongan.getText()) || "".equals(txtIdPerusahaanLowongan.getText()));
    }
    public boolean checkIdInputLowongan(){
        return !"".equals(txtIdLowongan.getText());
    }
    
    public void show_lowonganlist(Perusahaan perusahaan){
        ArrayList<Lowongan> list = getLowonganList(perusahaan);
        DefaultTableModel model = (DefaultTableModel) tableLowongan.getModel();
        
//        CLEAR TABLE
        model.setRowCount(0);
//        JOptionPane.showMessageDialog(null, list.size());
        Object[] row = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getNama();
            row[2] = list.get(i).getJumlahLowongan();
            row[3] = list.get(i).getIdPerusahaan();
            
            model.addRow(row);
        }
    }
    
    public ArrayList<Lowongan> getLowonganList(Perusahaan perusahaan){
//            ArrayList<Lowongan> lowonganList = new ArrayList<>();
            ArrayList<Lowongan> lowonganList = perusahaan.getDaftarLowongan();
            Connection con = db.getConnection();
            String query = "SELECT * from Lowongan where idPerusahaan = "+perusahaan.getId();
//            JOptionPane.showMessageDialog(null, query);
            Statement st;
            ResultSet rs;
        try {
            
            st = con.createStatement();
            rs = st.executeQuery(query);
            Lowongan lowongan;
            
            while (rs.next()) {
                lowongan = new Lowongan(rs.getString("id"), rs.getString("nama"), rs.getInt("jumlah_lowongan"), rs.getString("idperusahaan"));
                lowonganList.add(lowongan);
            }

        } catch (SQLException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
        return lowonganList;
    }
    
}
